/* Modelagem Basica */

CLIENTE

NOME - CARACTER(30)
CPF - NUMERICO(11)
EMAIL - CARACTER(30)
TELEFONE - CARACTER(30)
ENDERECO - CARACTER(100
SEXO - CARACTER(1)


/* PROCESSOS DE MODELAGEM */

MODELAGEM CONCEITUAL - RASCUNHO 
MODELAGEM LOGICA - QUALQUER PROGRAMA DE MODELAGEM 
MODELAGEM FISICA - SCRIPTS DE BANCO





/* INICIANDO A MODELAGEM FISICA */
		/* CRIANDO O BANCO DE DADOS */
			CREATE DATABASE PROJETO;

		/* CONECTANDO-SE AO BANCO */
			USE PROJETO;
			
		/* CRIANDO A TABELA CLIENTES */
			CREATE TABLE CLIENTE(
				NOME VARCHAR(30),
				SEXO CHAR(1),
				EMAIL VARCHAR(30),
				CPF INT(11),
				TELEFONE VARCHAR(30),
				ENDERECO VARCHAR(100)
			);
			
		/* VERIFICANDO AS TABELAS DO BANCO */ 
			SHOW TABLES;
			
		/* DESCOBRINDO A ESTRUTURA DE UMA TABELA */ 
			DESCRIBE NOME_DA_TABLEA;
				OU
			DESC NOME_DA_TABLEA;
			
		/* INSERINDO DADOS NA TABELA */ 
			/* FORMA 01 - OMITINDO AS COLUNAS(OS DADOS PRECISAO VIR NA SEQUENCIA QUE ESTA NA TABELA) */
				INSERT INTO CLIENTE VALUES('JOAO', 'M', 'JOAO@GMAIL.COM', 988638273, '22923110', 'MAIA LACERDA - ESTACIO - RIO DE JANEIRO -RJ');
			
				INSERT INTO CLIENTE VALUES('CELIA', 'F', 'CELIA@GMAIL.COM', 541521456, '25078869', 'RIACHUELO - CENTRO - RIO DE JANEIRO - RJ');
				
				INSERT INTO CLIENTE VALUE('JORGE', 'M', NULL, 885755896, '58748895', 'OSCAR CURY - BOM RETIRO - PATOS DE MINAS - MG');
				
			/* FORMA 02 - COLOCANDO AS COLUNAS */
				INSERT INTO CLIENTE(NOME, SEXO, ENDERECO, TELEFONE, CPF) VALUES('LILIAN', 'F', 'SENADOR SOARES - TIJUCA - RIO DE JANEIRO - RJ', '947785696', 887774856);

			/* FORMA 03 - INSERT COMPACTO - SOMENTE MYSQL */
				INSERT INTO CLIENTE VALUES
					('ANA', 'F', 'ANA@GLOBO.COM', 852548962, '548556985', 'PRESS ANTONIO CARLOS - CENTRO - SAO PAULO - SP'),
					('CARLA', 'F', 'CARLA@TERATI.COM.BR', 7745828, '66587458', 'SAMUEL SILVA - CENTRO - BELO HORIZONTE - MG');

/* O COMANDO SELECT 
selecao projecao e juncao
*/ 
		SELECT NOW();

		SELECT 'Keplin Dheison';

		SELECT 'BANCO DE DADOS';

/* ALIAS DE COLUNA */

SELECT NOME AS 'CLIENTE', SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDERECO, NOW() AS 'DATA' FROM CLIENTE;



/* APENAS PARA FINS ACADEMICOS */

SELECT * FROM CLIENTE;

/* FILTRANDO DADOS COM WHERE E LIKE */

SELECT NOME, TELEFONE FROM CLIENTE;

/* FILTRANDO */ 

SELECT
	NOME, SEXO 
FROM 
	CLIENTE
WHERE 
	SEXO = 'M';


SELECT
	NOME, SEXO 
FROM
	CLIENTE
WHERE 
	SEXO = 'F';


SELECT 
	NOME, SEXO 
FROM 
	CLIENTE
WHERE 
	ENDERECO = 'RJ';

/* UTILIZANDO O LIKE */


SELECT 
	NOME, SEXO 
FROM 
	CLIENTE
WHERE
	ENDERECO 
LIKE 
	'%RJ';
















































